FROM jenkins/jenkinsfile-runner

USER root

RUN apt-get update && \
    apt-get -y --no-install-recommends install apt-transport-https \
      ca-certificates \
      curl \
      gnupg2 \
      software-properties-common && \
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
    add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
     $(lsb_release -cs) \
     stable" && \
    apt-get update && \
    apt-get -y --no-install-recommends install docker-ce && \
    apt-get clean || truedok

#RUN deb http://ftp.de.debian.org/debian sid main
#libseccomp2 - 2.3.1-2.1+deb9u1
# RUN apt-get install libseccomp2=2.3.0 libc6=2.14 init-system-helpers=1.48
# #ENTRYPOINT [ "sh", "-c", "echo $(lsb_release -cs)"]

RUN curl -k -O -L https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/containerd.io_1.3.7-1_amd64.deb && \
   curl -k -O -L  https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce-cli_19.03.13~3-0~debian-stretch_amd64.deb && \
   curl -k -O -L  https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_19.03.13~3-0~debian-stretch_amd64.deb

RUN apt install -q -y gdebi-core

#RUN apt install -q -y --allow-downgrades ./containerd.io_1.3.7-1_amd64.deb && \
#     apt install -q -y --allow-downgrades ./docker-ce-cli_19.03.13~3-0~debian-stretch_amd64.deb && \
#     apt install -q -y --allow-downgrades ./docker-ce_19.03.13~3-0~debian-stretch_amd64.deb || true

RUN gdebi ./containerd.io_1.3.7-1_amd64.deb && \
    gdebi ./docker-ce-cli_19.03.13~3-0~debian-stretch_amd64.deb && \
    gdebi ./docker-ce_19.03.13~3-0~debian-stretch_amd64.deb || true

RUN curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

#ENTRYPOINT [ "tail" ,"-f" ,"/dev/null" ]