FROM jenkins/jenkinsfile-runner

RUN rm -rf /var/lib/apt/lists/* && apt-get clean

RUN apt-get update --fix-missing && \
  #   apt-get -y --no-install-recommends install git apt-transport-https \
  #     ca-certificates \
  #     curl \
  #     gnupg2 \
  #     software-properties-common && \
  #   curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | apt-key add - && \
  #   apt-key fingerprint 0EBFCD88 && \
  #   add-apt-repository \
  #  "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
  #  $(lsb_release -cs) \
  #  stable" && \
  #  apt-get update && \
   curl -fsSL http://get.docker.com 29 -o get-docker.sh && chmox +x get-docker.sh
   
RUN get-docker.sh
   #apt-get -y --no-install-recommends install docker-ce && \
   #apt-get clean

RUN curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

RUN useradd -ms /bin/bash jenkins
RUN usermod -u 1000 jenkins